apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: broker
spec:
  deploymentPlan:
    size: 2
    image: registry.redhat.io/amq7/amq-broker:7.8
    initImage: image-registry.openshift-image-registry.svc:5000/myamq/amq-broker-init
  acceptors:
    - name: amqp
      protocols: amqp
      port: 5672
  console:
    expose: true
